bookings/urls.py
from django.urls import path
from . import views

app_name = 'bookings'

urlpatterns = [
    path('<int:category_id>/', views.bookservice, name='bookservice'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('booking_confirmation/<int:booking_id>/', views.booking_confirmation, name='booking_confirmation'),
    path('esewa-response/<int:booking_id>/', views.esewa_response, name='esewa-response'),
    path('esewarequest/<int:booking_id>/', views.esewarequest, name='esewarequest')
    
]

perfectsolution/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_website.urls')),
    path('bookings/', include('bookings.urls')),
    path('accounts/', include('allauth.urls')),
    path('home/',TemplateView.as_view(template_name='dashboard/home.html'), name='home')
] + debug_toolbar_urls() 

templates/review_form.html
<!-- add_review.html / edit_review.html -->
<h2>{% if review %}Edit{% else %}Add{% endif %} Your Review</h2>
<form method="post">
	{% csrf_token %} {{ form.as_p }}
	<button type="submit">
		{% if review %}Update{% else %}Submit{% endif %} Review
	</button>
</form>

templates/shop-detail.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <meta name="description" content="" />
    <meta name="author" content="Tooplate" />

    <title>Perfect solution - Product Detail Page</title>

    <!-- CSS FILES -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />

    <link
      href="https://fonts.googleapis.com/css2?family=League+Spartan:wght@100;300;400;600;700&display=swap"
      rel="stylesheet"
    />

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap-icons.css' %}" />
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/categories-slider.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'css/tooplate-moso-interior.css' %}"
    />
    <!--

Tooplate 2133 Moso Interior

https://www.tooplate.com/view/2133-moso-interior

Bootstrap 5 HTML CSS Template

-->
  </head>

  <body class="shop-detail-page">
    <nav class="navbar navbar-expand-lg bg-light fixed-top shadow-lg">
			<div class="container">
				<a class="navbar-brand" href="{% url 'homepage' %}"
					>Perfect <span class="tooplate-red">Solu</span
					><span class="tooplate-green">tion</span></a
				>

				<button
					class="navbar-toggler"
					type="button"
					data-bs-toggle="collapse"
					data-bs-target="#navbarNav"
					aria-controls="navbarNav"
					aria-expanded="false"
					aria-label="Toggle navigation"
				>
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav ms-auto">
						<li class="nav-item">
							<a class="nav-link click-scroll" href="#section_1">home</a>
						</li>

						<li class="nav-item">
							<a class="nav-link click-scroll" href="#section_2">About</a>
						</li>

						<li class="nav-item">
							<a class="nav-link click-scroll" href="#section_4">Service</a>
						</li>
						{% if user.is_authenticated %}
						<li class="nav-item">
							<a class="nav-link" href="#section_4">Logout</a>
						</li>
						{%else %}
						<li class="nav-item">
							<a class="nav-link" href="#section_4">Login</a>
						</li>
						{%endif%}

						<li class="nav-item">
							<a class="nav-link click-scroll" href="#section_5">Review</a>
						</li>
						<li class="nav-item">
							<a class="nav-link click-scroll" href="#section_5">Contact</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>

    <main>
      <header
        class="site-header d-flex justify-content-center align-items-center" style="background-image: url('{{ service.image.url }}');"
      >
        <div class="container">
          <div class="row">
            <div class="col-lg-12 col-12">
              <h1 class="text-white">{{service.name}}</h1>
            </div>
          </div>
        </div>
      </header>

      <section class="shop-detail-bar section-bg">
        <div class="container">
          <div class="row">
            <div class="col-lg-7 col-md-8 col-12 d-flex">
              <p class="shop-detail-bar-wrap d-flex flex-wrap mb-0">
                <span class="me-2">Price:</span>

                <strong class="shop-pricing-text">RS</strong>
              </p>

              <p
                class="shop-detail-bar-wrap d-flex flex-wrap ms-lg-5 ms-4 mb-0"
              >
                <span class="me-2">Condition:</span>

                <strong class="shop-condition-text">Good</strong>
              </p>

              <p
                class="shop-detail-bar-wrap d-flex flex-wrap ms-lg-5 ms-4 mb-0"
              >
                <span class="me-2">Type:</span>

                <strong>Family</strong>
              </p>
            </div>

            <div
              class="col-lg-5 col-md-4 col-12 social-share d-flex align-items-center ms-lg-auto mt-3 mt-lg-0 mt-md-0"
            >
              <p class="mb-0 me-3 ms-lg-auto ms-md-auto">Share:</p>

              <ul class="social-icon">
                <li class="social-icon-item">
                  <a
                    href="#"
                    class="social-icon-link social-icon-twitter bi-twitter"
                  ></a>
                </li>

                <li class="social-icon-item">
                  <a
                    href="#"
                    class="social-icon-link social-icon-facebook bi-facebook"
                  ></a>
                </li>

                <li class="social-icon-item">
                  <a
                    href="#"
                    class="social-icon-link social-icon-pinterest bi-pinterest"
                  ></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      <section class="shop-detail-section">
        <section class="about-section section-padding" id="section_2">
          <div class="container">
            <div class="row align-items-center">
              {% comment %} Left side for description {% endcomment %}
              <div class="col-lg-5 col-12">
                <small class="section-small-title">Our Story</small>
                <h2 class="mt-2 mb-4">
                  <span class="text-muted">Introducing</span> Perfect Solution
                </h2>
                <h4 class="text-muted mb-3">
                  Since 1986, We crafted interior products for better spaces
                </h4>
                <p>{{ service.description }}</p>
              </div>

              <div class="col-lg-7 col-12">
                <div class="wrapper">
                  <div class="outer">
                    {% for category in categories %}
                    <a href="{% url 'category' category.id %}">
                      <div class="card" style="--delay: -1">
                        <div class="img-container">
                          
                          {% if category.photo %}
                          <img src="{{category.photo.url}}" alt="Image 1" /> 
                          {% else %}
                          <p>no photo available</p>
                          {% endif %}
                            
                        </div>
                        <div class="details">
                          <p>{{category.name}}</p>
                          <div class="btn-clss">
                            <button>Learn more</button>
                          </div>
                        </div>
                      </div>
                    </a>
                    {% endfor %}
                    {% comment %} <div class="card" style="--delay: 2">
                      <div class="img-container">
                        <img
                          src="{% static 'Images/img-4.jpg' %}"
                          alt="Image 5"
                        />
                      </div>
                      <div class="details">
                        <p>Teacher & Advertiser</p>
                        <div class="btn-clss">
                          <button>Learn more</button>
                        </div>
                      </div>
                    </div> {% endcomment %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </section>

      <div class="container-button">
        
        {% if service.id and categories %}
          
        {% elif service.id %}
          <button>
            <a href="{% url 'bookings:bookservice' service.id %}">Book Service</a>
          </button>
        {% endif %}
        

      </button>
      </div>  

      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
        <path
          fill="#36363e"
          fill-opacity="1"
          d="M0,96L40,117.3C80,139,160,181,240,186.7C320,192,400,160,480,149.3C560,139,640,149,720,176C800,203,880,245,960,250.7C1040,256,1120,224,1200,229.3C1280,235,1360,277,1400,298.7L1440,320L1440,320L1400,320C1360,320,1280,320,1200,320C1120,320,1040,320,960,320C880,320,800,320,720,320C640,320,560,320,480,320C400,320,320,320,240,320C160,320,80,320,40,320L0,320Z"
        ></path>
      </svg>
    </main>

    <footer class="site-footer section-padding">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-5 col-12 mb-3">
            <h3>
              <a href="index.html" class="custom-link mb-1"
                >Perfect solution Interior</a
              >
            </h3>

            <p class="text-white">
              Since 1986, We crafted interior products for better spaces
            </p>

            <p class="text-white">
              <a href="" target="_parent"
                >Perfect Solution</a
              >
            </p>
          </div>

          <div class="col-lg-3 col-md-3 col-12 ms-lg-auto mb-3">
            <h3 class="text-white mb-3">Store</h3>

            <p class="text-white mt-2">
              <i class="bi-geo-alt"></i>
              Berlin, Germany
            </p>
          </div>

          <div class="col-lg-3 col-md-4 col-12 mb-3">
            <h3 class="text-white mb-3">Contact Info</h3>

            <p class="text-white mb-1">
              <i class="bi-telephone me-1"></i>

              <a href="tel: 090-080-0760" class="text-white"> 090-080-0760 </a>
            </p>

            <p class="text-white mb-0">
              <i class="bi-envelope me-1"></i>

              <a href="mailto:info@company.com" class="text-white">
                info@company.com
              </a>
            </p>
          </div>

          <div
            class="col-lg-6 col-md-7 copyright-text-wrap col-12 d-flex flex-wrap align-items-center mt-4 ms-auto"
          >
            <p class="copyright-text mb-0 me-4">Copyright © PErfect solution</p>

            <ul class="social-icon">
              <li class="social-icon-item">
                <a
                  href="#"
                  class="social-icon-link social-icon-twitter bi-twitter"
                ></a>
              </li>

              <li class="social-icon-item">
                <a
                  href="#"
                  class="social-icon-link social-icon-facebook bi-facebook"
                ></a>
              </li>

              <li class="social-icon-item">
                <a
                  href="#"
                  class="social-icon-link social-icon-instagram bi-instagram"
                ></a>
              </li>

              <li class="social-icon-item">
                <a
                  href="#"
                  class="social-icon-link social-icon-pinterest bi-pinterest"
                ></a>
              </li>

              <li class="social-icon-item">
                <a
                  href="#"
                  class="social-icon-link social-icon-whatsapp bi-whatsapp"
                ></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

    <!-- JAVASCRIPT FILES -->
    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/click-scroll.js"></script>
    <script src="js/jquery.backstretch.min.js"></script>
    <script src="js/owl.carousel.min.js"></script>
    <script src="js/custom.js"></script>
  </body>
</html>